### PR TITLE
Added a base composer.json for easy integration with php projects

### PR DESCRIPTION
**Pull request by chewett**
Pull request in relation to https://github.com/benpickles/peity/issues/86

### CODE REVIEW

**Comment by chewett** [comment]
Has there been any progress here?

**Comment by benpickles** [comment]
Sorry, totally forgot about this.

**Comment by benpickles** [comment]
https://packagist.org/packages/benpickles/peity

Would you mind checking that it works as intended?

**Comment by chewett** [comment]
Works perfectly, Many thanks!

**Pull request merged**
