### PR TITLE
Expose an item's value on bar and pie slice SVG nodes

### LINKED ISSUE #9: label on each value?
is there a way to see what the value is for each bar in a bar chart?

thanks,
tim

### LINKED ISSUE #55: insert a data-value attribute on elements
everywhere that has svgElement('shape',{attributes object})
in the attributes object, add a line
"data-value":value

this enables code like
$("svg rect").hover(function(){console.log($(this).attr("data-value"));},function(){});
and obviously more clever uses of the value that gave rise to the representation

### LINKED ISSUE #71: Add 'title' to svg element
Would it be possible to add a 'title' to the svg element which shows the text when moving the mouse over that element?

### PR DESCRIPTION
**Pull request by benpickles**
The intention is that this can drive tooltips, for example: https://jsbin.com/vufayan/edit?html,js,output

- Addresses #2.
- Fixes #9.
- Addresses #29.
- Fixes #55.
- Fixes #71.
- Closes #84.

### CODE REVIEW

**Comment by oblomki** [comment]
Hi Ben,

Your JSBin doesn't seem to work.

```
"TypeError: $(...).peity is not a function
    at nuwajafiti.js:1:910"
```

**Comment by benpickles** [comment]
@oblomki sorry, that's fixed now.

**Comment by oblomki** [comment]
Great, thanks.

**Comment by crivote** [comment]
Very useful feature! thanks a lot

**Pull request merged**
